export const MAX_NUM_OF_INVITE_MESSAGE_CHARACTERS = 300;
export const MIN_ASSIGNMENT_SOLUTION_GRADE = 0;
export const MAX_ASSIGNMENT_SOLUTION_GRADE = 100;
export const SEND_STATISTICS_INTERVAL = 10000;
